services:
  telegram-bot:
    build: .
    container_name: telegram-bot
    env_file:
      - .env
    restart: unless-stopped

  webview:
    build: ./WebView
    container_name: webview
    env_file:
      - .env
    ports:
      - "8080:8080"  # 8080:8080

